window.BASE_INFO = {
    mainTitle: 'TEST YOUR KNOWLEDGE',
    actual: 'Not an actual patient.',
    date: 'August 2022. PP-XEL-GLB-1410',
    congratulations: 'Congratulations!',
    promise: 'You have successfully tested your knowledge of XELJANZ!',
    qrCode: `Interested in VISITING THE VIRTUAL BOOTH?<br>Scan the QR code below.`,
    closeBtn: 'Close',
    questionRemaining: 'question remaining',
    allCongrats: `<p><span style="color: #e30847;">Congratulations!</span><br/>You have successfully tested your knowledge of XELJANZ!</p>`,
    myKnowledge: 'My knowledge of XELJANZ has:',
    notChanged: 'Not changed',
    improved: 'Somewhat improved',
    greatImproved: 'Greatly improved',
    resetBtn: 'Reset',
    viewAnswerBtn: 'View Answer',
    finishBtn: 'Finish',
    addInfoBtn: 'Additional Information',
    nextQuestionBtn: 'Next Question',
    yourAnswer: 'Your answer',
    tip: 'Tip',
    studyDesign: 'Study Design',
    safetyProfile: 'Safety Profile',
    references: 'References',
    stillHere: 'STILL HERE?',
    tapToContinue: 'Tap to continue',
    exitSession: 'Exit session',
    slideToSelect: `Slide button to select your answer.<br/>Press ‘VIEW ANSWER’ to see the results.`,
    tapAnywhere: 'Tap anywhere to begin',
    loading: 'Loading',
    correctAnswer: 'Correct answer'
}